export const MODULE_LIBRARY = [
  {
    id: 'glasses',
    name: 'Glasses',
    color: '#7C3AED',
    renderType: 'geometry',
    mountStyle: 'holder',
    textureRule: 'followFinish',
    width: 165,
    depth: 70,
    height: 65,
    minWidth: 165,
    maxWidth: 2000,
    minDepth: 70,
    maxDepth: 70,
    minHeight: 65,
    maxHeight: 65,
  },
  {
    id: 'watch_pad',
    name: 'Watch Pad',
    color: '#2563EB',
    renderType: 'geometry',
    mountStyle: 'holder',
    textureRule: 'onlyVelvet',
    width: 40,
    depth: 72,
    height: 32,
    minWidth: 40,
    maxWidth: 40,
    minDepth: 72,
    maxDepth: 72,
    minHeight: 32,
    maxHeight: 32,
  },
  {
    id: 'rings_4_strokes',
    name: 'Rings 4 Strokes',
    color: '#E11D48',
    renderType: 'model',
    mountStyle: 'cover',
    textureRule: 'onlyVelvet',
    modelPath: '/models/modules/ringstrokes.glb',
    width: 80,
    depth: 80,
    height: 38,
    minWidth: 80,
    maxWidth: 2000,
    minDepth: 80,
    maxDepth: 80,
    minHeight: 38,
    maxHeight: 100,
  },
  {
    id: 'rings_1_stroke',
    name: 'Rings 1 Stroke',
    color: '#F97316',
    renderType: 'model',
    mountStyle: 'cover',
    textureRule: 'onlyVelvet',
    modelPath: '/models/modules/ringstrokes.glb',
    width: 80,
    depth: 20,
    height: 38,
    minWidth: 80,
    maxWidth: 2000,
    minDepth: 20,
    maxDepth: 20,
    minHeight: 38,
    maxHeight: 100,
  },
  {
    id: 'cover_holes_only',
    name: 'Cover Holes Only',
    color: '#14B8A6',
    renderType: 'model',
    mountStyle: 'cover',
    textureRule: 'onlyLeather',
    modelPath: '/models/modules/holesonly.glb',
    width: 100,
    depth: 100,
    height: 3,
    minWidth: 100,
    maxWidth: 300,
    minDepth: 100,
    maxDepth: 300,
    minHeight: 3,
    maxHeight: 3,
  },
  {
    id: 'cover_lip_with_holes',
    name: 'Cover Lip With Holes',
    color: '#0EA5E9',
    renderType: 'model',
    mountStyle: 'cover',
    textureRule: 'outsideLeatherBottomVelvet',
    modelPath: '/models/modules/lipwithholes.glb',
    width: 100,
    depth: 100,
    height: 3,
    minWidth: 100,
    maxWidth: 300,
    minDepth: 100,
    maxDepth: 300,
    minHeight: 3,
    maxHeight: 3,
  },
  {
    id: 'cover_lip_no_holes',
    name: 'Cover Lip No Holes',
    color: '#8B5CF6',
    renderType: 'model',
    mountStyle: 'cover',
    textureRule: 'leatherTopVelvetBottom',
    modelPath: '/models/modules/lipNoholes.glb',
    width: 100,
    depth: 100,
    height: 3,
    minWidth: 100,
    maxWidth: 300,
    minDepth: 100,
    maxDepth: 300,
    minHeight: 3,
    maxHeight: 3,
  },
  {
    id: 'cover_no_lip_no_holes',
    name: 'Cover No Lip No Holes',
    color: '#64748B',
    renderType: 'model',
    mountStyle: 'cover',
    textureRule: 'outsideLeatherBottomVelvet',
    modelPath: '/models/modules/nolipnoholes.glb',
    width: 100,
    depth: 100,
    height: 3,
    minWidth: 100,
    maxWidth: 300,
    minDepth: 100,
    maxDepth: 300,
    minHeight: 3,
    maxHeight: 3,
  },
];

export const MODULE_MAP = Object.fromEntries(
  MODULE_LIBRARY.map((module) => [module.id, module])
);

export const getModuleDefinition = (moduleId) => MODULE_MAP[moduleId] || null;
