import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
    gb: { // English
        // TopBar
        dashboard: 'Dashboard',
        profileSettings: 'Profile Settings',
        designHistory: 'Design History',
        templates: 'Templates',
        logout: 'Log Out',
        // Sidebar
        traySize: 'Tray Size',
        millimeter: 'Millimeter',
        width: 'Width (mm)',
        depth: 'Depth (mm)',
        height: 'Height (mm)',
        gridRows: 'Grid Rows',
        gridCols: 'Grid Cols',
        widthDesc: 'Min. 50mm, Max. 2000mm',
        depthDesc: 'Min. 50mm, Max. 1200mm',
        heightDesc: 'Min. 35mm, Max. 500mm',
        rowsDesc: 'Horizontal Slots',
        colsDesc: 'Vertical Slots',
        trayFinish: 'Tray Finish',
        leatherWithVelvet: 'Leather with Velvet',
        fullLeather: 'Full Leather',
        topCover: 'Top Cover',
        horizontalDividers: 'Horizontal Dividers',
        verticalDividers: 'Vertical Dividers',
        yDivider: 'Y Divider',
        xDivider: 'X Divider',
        fromFront: 'From Front',
        fromLeft: 'From Left',
        modules: 'Modules',
        glasses: 'Glasses',
        finish: 'Finish:',
        size: 'Size',
        selectColor: 'SELECT COLOR:',
        gray: 'Gray (B2)',
        requestQuote: 'Request Quote',
        // TrayOverview
        trayOverview: 'Tray Overview',
        overviewDesc: 'A detailed view of your custom-designed modular tray, featuring selected materials, dividers, and module types.',
        specifications: 'Specifications',
        quantity: 'Quantity',
        editConfiguration: 'Edit Configuration',
        download3DModel: 'Download 3D Model',
        trayType: 'Tray Type',
        dividers: 'Dividers',
        material: 'Material',
        color: 'Color',
        standard: 'Standard',
        yesAdjustedSpc: 'Yes (Adjusted Spacing)',
        earringsRings: 'Earrings, Rings',
        wood: 'Wood',
        black: 'Black',
        saved: 'Saved',
        topView: 'Top View',
        threeDView: '3D View',
        newDesign: 'New Design',
    },
    sa: { // Arabic
        dashboard: 'لوحة القيادة',
        profileSettings: 'إعدادات الملف الشخصي',
        designHistory: 'سجل التصميم',
        templates: 'القوالب',
        logout: 'تسجيل الخروج',
        traySize: 'حجم الدرج',
        millimeter: 'مليمتر',
        width: 'العرض (مم)',
        depth: 'العمق (مم)',
        height: 'الارتفاع (مم)',
        gridRows: 'صفوف الشبكة',
        gridCols: 'أعمدة الشبكة',
        widthDesc: 'الحد الأدنى 50 مم، الحد الأقصى 2000 مم',
        depthDesc: 'الحد الأدنى 50 مم، الحد الأقصى 1200 مم',
        heightDesc: 'الحد الأدنى 35 مم، الحد الأقصى 500 مم',
        rowsDesc: 'فتحات أفقية',
        colsDesc: 'فتحات عمودية',
        trayFinish: 'لمسة نهائية للدرج',
        leatherWithVelvet: 'جلد مع مخمل',
        fullLeather: 'جلد كامل',
        topCover: 'الغطاء العلوي',
        horizontalDividers: 'فواصل أفقية',
        verticalDividers: 'فواصل عمودية',
        yDivider: 'فاصل Y',
        xDivider: 'فاصل X',
        fromFront: 'من الأمام',
        fromLeft: 'من اليسار',
        modules: 'الوحدات',
        glasses: 'نظارات',
        finish: 'اللمسة النهائية:',
        size: 'الحجم',
        selectColor: 'اختر اللون:',
        gray: 'رمادي (B2)',
        requestQuote: 'طلب عرض سعر',
        trayOverview: 'نظرة عامة على الدرج',
        overviewDesc: 'عرض مفصل للدرج المعياري المصمم خصيصًا لك، والذي يتميز بالمواد المختارة والفواصل وأنواع الوحدات.',
        specifications: 'المواصفات',
        quantity: 'الكمية',
        editConfiguration: 'تعديل التكوين',
        download3DModel: 'تحميل نموذج ثلاثي الأبعاد',
        trayType: 'نوع الدرج',
        dividers: 'الفواصل',
        material: 'المادة',
        color: 'اللون',
        standard: 'قياسي',
        yesAdjustedSpc: 'نعم (تباعد معدل)',
        earringsRings: 'أقراط، خواتم',
        wood: 'خشب',
        black: 'أسود',
        saved: 'تم الحفظ',
        topView: 'عرض علوي',
        threeDView: 'عرض ثلاثي الأبعاد',
        newDesign: 'تصميم جديد',
    },
    fr: { // French
        dashboard: 'Tableau de bord',
        profileSettings: 'Paramètres du profil',
        designHistory: 'Historique de conception',
        templates: 'Modèles',
        logout: 'Déconnexion',
        traySize: 'Taille du plateau',
        millimeter: 'Millimètre',
        width: 'Largeur (mm)',
        depth: 'Profondeur (mm)',
        height: 'Hauteur (mm)',
        gridRows: 'Lignes de grille',
        gridCols: 'Colonnes de grille',
        widthDesc: 'Min. 50mm, Max. 2000mm',
        depthDesc: 'Min. 50mm, Max. 1200mm',
        heightDesc: 'Min. 35mm, Max. 500mm',
        rowsDesc: 'Fentes horizontales',
        colsDesc: 'Fentes verticales',
        trayFinish: 'Finition du plateau',
        leatherWithVelvet: 'Cuir avec velours',
        fullLeather: 'Tout cuir',
        topCover: 'Couvercle supérieur',
        horizontalDividers: 'Diviseurs horizontaux',
        verticalDividers: 'Diviseurs verticaux',
        yDivider: 'Diviseur Y',
        xDivider: 'Diviseur X',
        fromFront: 'De face',
        fromLeft: 'De gauche',
        modules: 'Modules',
        glasses: 'Lunettes',
        finish: 'Finition :',
        size: 'Taille',
        selectColor: 'CHOISIR LA COULEUR :',
        gray: 'Gris (B2)',
        requestQuote: 'Demander un devis',
        trayOverview: 'Aperçu du plateau',
        overviewDesc: 'Une vue détaillée de votre plateau modulaire personnalisé, avec les matériaux sélectionnés, les diviseurs et les types de modules.',
        specifications: 'Spécifications',
        quantity: 'Quantité',
        editConfiguration: 'Modifier la configuration',
        download3DModel: 'Télécharger le modèle 3D',
        trayType: 'Type de plateau',
        dividers: 'Diviseurs',
        material: 'Matériau',
        color: 'Couleur',
        standard: 'Standard',
        yesAdjustedSpc: 'Oui (espacement ajusté)',
        earringsRings: 'Boucles d\'oreilles, Bagues',
        wood: 'Bois',
        black: 'Noir',
        saved: 'Enregistré',
        topView: 'Vue de dessus',
        threeDView: 'Vue 3D',
        newDesign: 'Nouveau design',
    },
    es: { // Spanish
        dashboard: 'Tablero',
        profileSettings: 'Ajustes de perfil',
        designHistory: 'Historial de diseño',
        templates: 'Plantillas',
        logout: 'Cerrar sesión',
        traySize: 'Tamaño de la bandeja',
        millimeter: 'Milímetro',
        width: 'Ancho (mm)',
        depth: 'Profundidad (mm)',
        height: 'Altura (mm)',
        gridRows: 'Filas de la cuadrícula',
        gridCols: 'Colonnes de la cuadrícula',
        widthDesc: 'Min. 50mm, Max. 2000mm',
        depthDesc: 'Min. 50mm, Max. 1200mm',
        heightDesc: 'Min. 35mm, Max. 500mm',
        rowsDesc: 'Ranuras horizontales',
        colsDesc: 'Ranuras verticales',
        trayFinish: 'Acabado de la bandeja',
        leatherWithVelvet: 'Cuero con terciopelo',
        fullLeather: 'Todo cuero',
        topCover: 'Cubierta superior',
        horizontalDividers: 'Divisores horizontales',
        verticalDividers: 'Divisores verticales',
        yDivider: 'Divisor Y',
        xDivider: 'Divisor X',
        fromFront: 'Desde el frente',
        fromLeft: 'Desde la izquierda',
        modules: 'Módulos',
        glasses: 'Gafas',
        finish: 'Acabado:',
        size: 'Tamaño',
        selectColor: 'SELECCIONAR COLOR:',
        gray: 'Gris (B2)',
        requestQuote: 'Solicitar presupuesto',
        trayOverview: 'Resumen de la bandeja',
        overviewDesc: 'Una vista detallada de su bandeja modular diseñada a medida, con materiales seleccionados, divisores y tipos de módulos.',
        specifications: 'Especificaciones',
        quantity: 'Cantidad',
        editConfiguration: 'Editar configuración',
        download3DModel: 'Descargar modelo 3D',
        trayType: 'Tipo de bandeja',
        dividers: 'Divisores',
        material: 'Material',
        color: 'Color',
        standard: 'Estándar',
        yesAdjustedSpc: 'Sí (espacio ajustado)',
        earringsRings: 'Pendientes, Anillos',
        wood: 'Madera',
        black: 'Negro',
        saved: 'Guardado',
        topView: 'Vista superior',
        threeDView: 'Vista 3D',
        newDesign: 'Nuevo diseño',
    },
    // Adding placeholders for others to make it "workable"
    nl: { traySize: 'Lade Formaat' },
    de: { traySize: 'Tablettgröße' },
    it: { traySize: 'Dimensioni Vassoio' },
    pt: { traySize: 'Tamanho da Bandeja' },
    ru: { traySize: 'Размер лотка' },
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('gb');

    const t = (key) => {
        return translations[language][key] || translations['gb'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
